// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjPOsNiBWN-Hgxm7sNGC-v311Pru_V2fA',
    appId: '1:52791726499:web:c3265346a39688a489ca16',
    messagingSenderId: '52791726499',
    projectId: 'infedu-df829',
    authDomain: 'infedu-df829.firebaseapp.com',
    storageBucket: 'infedu-df829.firebasestorage.app',
    measurementId: 'G-759RGJK7JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK66YXgs3IIGQENJMHUdHF7vqPUVamhag',
    appId: '1:52791726499:android:b09350f28331bf9589ca16',
    messagingSenderId: '52791726499',
    projectId: 'infedu-df829',
    storageBucket: 'infedu-df829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFwvwEv22LpA3PzHjCIXT500oyDU_KuVM',
    appId: '1:52791726499:ios:abe22672c48e978989ca16',
    messagingSenderId: '52791726499',
    projectId: 'infedu-df829',
    storageBucket: 'infedu-df829.firebasestorage.app',
    iosBundleId: 'com.example.infEduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFwvwEv22LpA3PzHjCIXT500oyDU_KuVM',
    appId: '1:52791726499:ios:abe22672c48e978989ca16',
    messagingSenderId: '52791726499',
    projectId: 'infedu-df829',
    storageBucket: 'infedu-df829.firebasestorage.app',
    iosBundleId: 'com.example.infEduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjPOsNiBWN-Hgxm7sNGC-v311Pru_V2fA',
    appId: '1:52791726499:web:4a7e958465ba42e489ca16',
    messagingSenderId: '52791726499',
    projectId: 'infedu-df829',
    authDomain: 'infedu-df829.firebaseapp.com',
    storageBucket: 'infedu-df829.firebasestorage.app',
    measurementId: 'G-6N533J26WT',
  );
}
